title: Pages Canary
description: The literal canary in the coal mine, at least when it comes to GitHub Pages

repository: github/pages-canary

# TEST
url: "http://example.com"
baseurl: "/something-random"

gems:
  - jekyll-github-metadata
  - jemoji
  - jekyll-coffeescript
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-seo-tag

foo: bar

theme: minima
