repository: github/pages-canary

gems:
  - jekyll-github-metadata
  - jemoji
  - jekyll-coffeescript
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll_test_plugin_malicious

foo: bar

theme: minima

exclude:
  - vendor/renderjson/README.md
  - vendor/renderjson/test.html
  - script/
  - Gemfile
  - Gemfile.lock
  - README.md
